[CmdletBinding()]
param(
    [string]$Version = '9.1.0',
    [switch]$SkipAnalyzer,
    [switch]$Pdq
)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$dist = Join-Path $root 'dist'
New-Item -ItemType Directory -Force $dist | Out-Null
$artifact = Join-Path $dist 'NMMTools.ps1'

# Build provenance. Captured once and reused for the header comment, the runtime
# block, and the success message, so the three cannot drift apart.
#
# $ErrorActionPreference is dropped to 'Continue' for the probe. git writes to
# stderr on any failure (not a repo, no git installed), and under 'Stop' a
# captured stderr stream can surface as a terminating error and take down the
# whole build over a cosmetic version string.
$buildDate = Get-Date
$commit    = 'unknown'
$prevEap   = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try {
    $rev = git -C $root rev-parse --short HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $rev) {
        $commit = ([string]$rev).Trim()
        $dirty = git -C $root status --porcelain 2>$null
        if ($LASTEXITCODE -eq 0 -and $dirty) { $commit = $commit + '-dirty' }
    }
} catch {
    # git missing entirely raises CommandNotFoundException, which is terminating
    # regardless of preference. An unknown commit is not a build failure.
    $commit = 'unknown'
} finally {
    $ErrorActionPreference = $prevEap
}

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add('#Requires -Version 5.1')
$parts.Add(('# NMM System Toolkit v{0} ({1}) | built {2:yyyy-MM-dd HH:mm} | GENERATED by build.ps1 - DO NOT EDIT' -f $Version, $commit, $buildDate))
$parts.Add('# Source: NMMToolkit repo. Edit src\, then rebuild.')

# 1. Param block must be the first statement in the artifact
$parts.Add((Get-Content (Join-Path $root 'src\entry\00-param.ps1') -Raw -Encoding UTF8))

# 1b. Provenance as real variables, readable at runtime by -Version. Must come
# after the param block, which has to remain the first statement in the file.
#
# Escape single quotes by doubling them before interpolating into the
# single-quoted literals below - an operator-supplied -Version containing a
# quote (e.g. -Version "9.1.0'") would otherwise break out of the literal and
# fail the parse gate. Applied to $commit too, since it lands in the same kind
# of literal even though git output doesn't normally contain a quote.
$versionEscaped = $Version -replace "'", "''"
$commitEscaped  = $commit  -replace "'", "''"
$parts.Add('#region provenance')
$parts.Add(("`$script:ToolkitVersion   = '{0}'" -f $versionEscaped))
$parts.Add(("`$script:ToolkitCommit    = '{0}'" -f $commitEscaped))
$parts.Add(("`$script:ToolkitBuildDate = '{0:yyyy-MM-dd HH:mm}'" -f $buildDate))
$parts.Add('#endregion')

# 2. Core, in numeric-prefix order
foreach ($f in (Get-ChildItem (Join-Path $root 'src\core') -Filter *.ps1 | Sort-Object Name)) {
    $parts.Add(('#region core\{0}' -f $f.Name))
    $parts.Add((Get-Content $f.FullName -Raw -Encoding UTF8))
    $parts.Add('#endregion')
}

# 3. Registry: psd1 content is a valid hashtable literal, assigned directly
$parts.Add('#region registry')
$parts.Add('$script:RegistryData =')
$parts.Add((Get-Content (Join-Path $root 'src\registry\tools.psd1') -Raw -Encoding UTF8))
$parts.Add('#endregion')

# 4. Tools
$toolFiles = @(Get-ChildItem (Join-Path $root 'src\tools') -Recurse -Filter *.ps1 | Sort-Object FullName)
if ($toolFiles.Count -eq 0) { throw 'No .ps1 files found in src\tools - aborting build' }
# FullName groups tools by category dir then file; relative order is stable across machines
foreach ($f in $toolFiles) {
    $parts.Add(('#region tools\{0}\{1}' -f $f.Directory.Name, $f.Name))
    $parts.Add((Get-Content $f.FullName -Raw -Encoding UTF8))
    $parts.Add('#endregion')
}

# 5. Entry point last
$parts.Add((Get-Content (Join-Path $root 'src\entry\99-main.ps1') -Raw -Encoding UTF8))

# Write the encoding explicitly rather than via Set-Content -Encoding UTF8, which
# means "UTF-8 with BOM" on PS 5.1 and "UTF-8 without BOM" on PS 7. Using it made
# the shipped bytes depend on which shell ran the build, so one commit could
# produce two different artifacts - which also defeats hash-comparing a deployed
# copy against the commit its -Version banner claims.
[System.IO.File]::WriteAllText($artifact, ($parts -join "`r`n"), (New-Object System.Text.UTF8Encoding($false)))

# Gate 1: parse
$tokens = $null; $parseErrors = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($artifact, [ref]$tokens, [ref]$parseErrors)
if ($parseErrors.Count -gt 0) {
    $parseErrors | ForEach-Object { Write-Host ('{0} (line {1})' -f $_.Message, $_.Extent.StartLineNumber) -ForegroundColor Red }
    throw ('Artifact has {0} parse error(s) - build failed' -f $parseErrors.Count)
}

# Gate 2: analyzer (errors only; warnings like PSAvoidUsingWriteHost are accepted)
if (-not $SkipAnalyzer) {
    Import-Module PSScriptAnalyzer
    $findings = Invoke-ScriptAnalyzer -Path $artifact -Severity Error
    if ($findings) {
        $findings | Format-Table RuleName, Line, Message -AutoSize | Out-String | Write-Host
        throw ('PSScriptAnalyzer found {0} error(s) - build failed' -f @($findings).Count)
    }
}

$sizeKB = [math]::Round((Get-Item $artifact).Length / 1KB)
Write-Host ('Built {0} ({1} KB, v{2} {3})' -f $artifact, $sizeKB, $Version, $commit) -ForegroundColor Green

# ---- 6. PDQ per-tool scripts (opt-in) ---------------------------------------
# Each emitted script is self-contained: the seven headless core files, a
# single-entry registry, one tool function, and an entry point. The console
# menu, usage store, WPF GUI and Jira cores are omitted - nothing under
# src\tools references them, and they are 2152 of the 2770 core lines.
if ($Pdq) {
    $pdqDir = Join-Path $dist 'pdq'
    # Wipe and recreate so a tool that loses its flag leaves no stale script
    # behind for someone to deploy.
    if (Test-Path $pdqDir) { Remove-Item $pdqDir -Recurse -Force }
    New-Item -ItemType Directory -Force $pdqDir | Out-Null

    $registryData = Import-PowerShellDataFile (Join-Path $root 'src\registry\tools.psd1')
    $headlessCore = @('01-bootstrap.ps1','02-output.ps1','03-results.ps1','04-dispatch.ps1',
                      '07-repair-helpers.ps1','08-browser-helpers.ps1',
                      '11-diagnostic-bundle-helpers.ps1')

    $q = { param([string]$s) $s -replace "'", "''" }

    # Every function the toolkit defines anywhere under src\. Used to gate emitted
    # scripts on self-containment. Deliberately not Get-Command: that resolves
    # against whatever modules exist on the build machine, so the verdict would
    # vary by machine whenever a tool calls a cmdlet not installed locally.
    $srcFunctionNames = @()
    foreach ($sf in (Get-ChildItem (Join-Path $root 'src') -Recurse -Filter *.ps1)) {
        $srcFunctionNames += [regex]::Matches((Get-Content $sf.FullName -Raw), '(?m)^function\s+([\w-]+)') |
                             ForEach-Object { $_.Groups[1].Value }
    }
    $srcFunctionNames = @($srcFunctionNames | Sort-Object -Unique)

    $emitted = 0
    foreach ($tool in @($registryData.Tools)) {
        if (-not $tool.PdqDeployable) { continue }

        $toolFile = $toolFiles | Where-Object { $_.BaseName -eq $tool.Function } | Select-Object -First 1
        if (-not $toolFile) {
            throw ("PdqDeployable tool '{0}' declares Function '{1}' with no matching file under src\tools" -f $tool.Id, $tool.Function)
        }

        $g = New-Object System.Collections.Generic.List[string]
        $g.Add('#Requires -Version 5.1')
        $g.Add(('# NMM PDQ tool: {0} -> {1}' -f $tool.Id, $tool.Function))
        $g.Add(('# NMM System Toolkit v{0} ({1}) | built {2:yyyy-MM-dd HH:mm}' -f $Version, $commit, $buildDate))
        $g.Add('# GENERATED by build.ps1 -Pdq - DO NOT EDIT')
        $g.Add(('# Source: NMMToolkit repo, src\tools\{0}\{1}' -f $toolFile.Directory.Name, $toolFile.Name))
        $g.Add('')
        $g.Add('[CmdletBinding()]')
        $g.Add('param(')
        $g.Add('    [switch]$Force,      # required for Disruptive tools')
        $g.Add('    [string]$LogPath,    # directory for the session log file')
        $g.Add('    [switch]$Version     # print provenance and exit 0')
        $g.Add(')')
        $g.Add('')
        $g.Add('#region provenance')
        $g.Add(("`$script:ToolkitVersion   = '{0}'" -f (& $q $Version)))
        $g.Add(("`$script:ToolkitCommit    = '{0}'" -f (& $q $commit)))
        $g.Add(("`$script:ToolkitBuildDate = '{0:yyyy-MM-dd HH:mm}'" -f $buildDate))
        $g.Add(("`$script:PdqToolId        = '{0}'" -f (& $q $tool.Id)))
        $g.Add('#endregion')

        foreach ($name in $headlessCore) {
            $g.Add(('#region core\{0}' -f $name))
            $g.Add((Get-Content (Join-Path $root ('src\core\' + $name)) -Raw -Encoding UTF8))
            $g.Add('#endregion')
        }

        $g.Add('#region registry')
        $g.Add('$script:RegistryData = @{ Tools = @(')
        $g.Add('    @{')
        $g.Add(("        Id            = '{0}'" -f (& $q $tool.Id)))
        $g.Add(("        LegacyId      = '{0}'" -f (& $q $tool.LegacyId)))
        $g.Add(("        Name          = '{0}'" -f (& $q $tool.Name)))
        $g.Add(("        Category      = '{0}'" -f (& $q $tool.Category)))
        $g.Add(("        Function      = '{0}'" -f (& $q $tool.Function)))
        $g.Add(("        Description   = '{0}'" -f (& $q $tool.Description)))
        $g.Add(("        RequiresAdmin = `${0}" -f $tool.RequiresAdmin))
        $g.Add(("        SilentCapable = `${0}" -f $tool.SilentCapable))
        $g.Add(("        PdqDeployable = `${0}" -f $tool.PdqDeployable))
        $g.Add(("        Risk          = '{0}'" -f (& $q $tool.Risk)))
        $g.Add(("        Tags          = @({0})" -f ((@($tool.Tags) | ForEach-Object { "'" + (& $q $_) + "'" }) -join ',')))
        $g.Add('    }')
        $g.Add(') }')
        $g.Add('#endregion')

        $g.Add(('#region tool\{0}' -f $toolFile.Name))
        $g.Add((Get-Content $toolFile.FullName -Raw -Encoding UTF8))
        $g.Add('#endregion')

        $g.Add('# ---- Entry point ----')
        $g.Add('# Sink first: the default Console sink emits via Write-Host, which PDQ')
        $g.Add('# cannot capture, and -Version exists precisely to be readable here.')
        $g.Add('Set-OutputSink -Sink Pdq -LogDirectory $LogPath')
        $g.Add('')
        $g.Add('if ($Version) {')
        $g.Add("    Write-ToolOutput ('NMM PDQ tool: {0}' -f `$script:PdqToolId) -Level Info")
        $g.Add("    Write-ToolOutput ('Toolkit v{0}' -f `$script:ToolkitVersion) -Level Info")
        $g.Add("    Write-ToolOutput ('Commit: {0}' -f `$script:ToolkitCommit) -Level Info")
        $g.Add("    Write-ToolOutput ('Built: {0}' -f `$script:ToolkitBuildDate) -Level Info")
        $g.Add('    exit 0')
        $g.Add('}')
        $g.Add('')
        $g.Add('$script:IsAdmin = Test-IsAdmin')
        $g.Add('')
        $g.Add('# Resolve rather than index: with one entry, $script:RegistryData.Tools[0]')
        $g.Add('# can be a key lookup on a bare hashtable and return $null.')
        $g.Add('$tool = Resolve-NmmTool -Query $script:PdqToolId')
        $g.Add('if (-not $tool) {')
        $g.Add("    Write-ToolOutput ('Generated script is corrupt: tool {0} not in its own registry.' -f `$script:PdqToolId) -Level Error")
        $g.Add('    exit 1')
        $g.Add('}')
        $g.Add('')
        $g.Add('# Take the last pipeline object. Invoke-NmmTool does not suppress the')
        $g.Add('# success stream of the tool it calls, so a tool that leaks output would')
        $g.Add('# make $status an array. A switch over an array matches on its FIRST')
        $g.Add('# element, so a leaked line would exit on the wrong branch. The monolith')
        $g.Add('# is immune because it compares with -eq, which filters an array.')
        $g.Add('$status = @(Invoke-NmmTool -Tool $tool -Silent -Force:$Force)[-1]')
        $g.Add('')
        $g.Add('switch ($status) {')
        $g.Add("    'Success' { exit 0 }")
        $g.Add("    'Failed'  { exit 1 }")
        $g.Add("    'Warning' { exit 2 }")
        $g.Add("    'Skipped' { exit 3 }")
        $g.Add("    'Refused' { exit 4 }")
        $g.Add('    default   { exit 1 }')
        $g.Add('}')
        $g.Add('')
        $g.Add('# Backstop. An empty status array matches no switch clause at all, not')
        $g.Add('# even default, and execution would otherwise fall off the end and exit 0.')
        $g.Add('exit 1')

        $outFile = Join-Path $pdqDir ($tool.Id + '.ps1')
        [System.IO.File]::WriteAllText($outFile, ($g -join "`r`n"), (New-Object System.Text.UTF8Encoding($false)))

        $pdqParseErrors = $null
        [void][System.Management.Automation.Language.Parser]::ParseFile($outFile, [ref]$null, [ref]$pdqParseErrors)
        if ($pdqParseErrors.Count -gt 0) {
            $pdqParseErrors | ForEach-Object { Write-Host ('{0} (line {1})' -f $_.Message, $_.Extent.StartLineNumber) -ForegroundColor Red }
            throw ("PDQ script for '{0}' has {1} parse error(s) - build failed" -f $tool.Id, $pdqParseErrors.Count)
        }

        if (-not $SkipAnalyzer) {
            $pdqFindings = Invoke-ScriptAnalyzer -Path $outFile -Severity Error
            if ($pdqFindings) {
                $pdqFindings | Format-Table RuleName, Line, Message -AutoSize | Out-String | Write-Host
                throw ("PDQ script for '{0}' has {1} analyzer error(s) - build failed" -f $tool.Id, @($pdqFindings).Count)
            }
        }

        # Self-containment gate. A tool that calls a sibling tool's function would
        # otherwise emit a script missing it, and the CommandNotFoundException would
        # be swallowed by the tool's own catch - reporting Success on every endpoint
        # while doing nothing useful.
        #
        # Candidate names come from two sources, not just invoked commands. The
        # toolkit dispatches sibling tools indirectly via `& $fn` (a variable), and
        # CommandAst.GetCommandName() returns empty for that call form - there is no
        # static name at the call site for the AST to see. The sibling names DO
        # survive as string literals (e.g. the $checks array Invoke-DiagnosticBundle
        # loops over), and those literals are emitted into the script verbatim, so
        # scanning StringConstantExpressionAst nodes recovers what the CommandAst
        # scan alone cannot. Comments are not string literals, so this can't repeat
        # the earlier false positive where a text scan matched a function name only
        # mentioned in documentation.
        #
        # Honest limitation: this is a fail-safe gate, not a proof. A tool that
        # computed a sibling's name at runtime (string concatenation, a config
        # lookup, etc.) would still slip past both the CommandAst and the literal
        # scan, because no static text anywhere in the script would spell the name
        # out. Both composite tools in this codebase use literals, so the scan
        # covers the known cases, but it does not cover every conceivable one.
        $emittedAst = [System.Management.Automation.Language.Parser]::ParseFile($outFile, [ref]$null, [ref]$null)
        $definedHere = @($emittedAst.FindAll({
            param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst]
        }, $true) | ForEach-Object { $_.Name })
        $calledHere = @($emittedAst.FindAll({
            param($n) $n -is [System.Management.Automation.Language.CommandAst]
        }, $true) | ForEach-Object { $_.GetCommandName() } | Where-Object { $_ })
        $literalsHere = @($emittedAst.FindAll({
            param($n) $n -is [System.Management.Automation.Language.StringConstantExpressionAst]
        }, $true) | ForEach-Object { $_.Value } | Where-Object { $_ })
        $candidatesHere = @($calledHere + $literalsHere | Sort-Object -Unique)
        $missing = @()
        foreach ($c in $candidatesHere) {
            if (($srcFunctionNames -contains $c) -and ($definedHere -notcontains $c)) {
                $missing += $c
            }
        }
        if ($missing.Count -gt 0) {
            throw ("PDQ script for '{0}' references toolkit function(s) it does not contain: {1}. A tool that invokes other tools cannot be packaged standalone - clear its PdqDeployable flag, or refactor it to not depend on sibling tools." -f $tool.Id, ($missing -join ', '))
        }

        $emitted++
    }

    Write-Host ('Emitted {0} PDQ script(s) to {1}' -f $emitted, $pdqDir) -ForegroundColor Green
}
