[CmdletBinding()]
param(
    [string]$Version = '9.1.0',
    [switch]$SkipAnalyzer
)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$dist = Join-Path $root 'dist'
New-Item -ItemType Directory -Force $dist | Out-Null
$artifact = Join-Path $dist 'NMMTools.ps1'

# Build provenance. Captured once and reused for the header comment, the runtime
# block, and the success message, so the three cannot drift apart.
#
# $ErrorActionPreference is dropped to 'Continue' for the probe. git writes to
# stderr on any failure (not a repo, no git installed), and under 'Stop' a
# captured stderr stream can surface as a terminating error and take down the
# whole build over a cosmetic version string.
$buildDate = Get-Date
$commit    = 'unknown'
$prevEap   = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try {
    $rev = git -C $root rev-parse --short HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $rev) {
        $commit = ([string]$rev).Trim()
        $dirty = git -C $root status --porcelain 2>$null
        if ($LASTEXITCODE -eq 0 -and $dirty) { $commit = $commit + '-dirty' }
    }
} catch {
    # git missing entirely raises CommandNotFoundException, which is terminating
    # regardless of preference. An unknown commit is not a build failure.
    $commit = 'unknown'
} finally {
    $ErrorActionPreference = $prevEap
}

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add('#Requires -Version 5.1')
$parts.Add(('# NMM System Toolkit v{0} ({1}) | built {2:yyyy-MM-dd HH:mm} | GENERATED by build.ps1 - DO NOT EDIT' -f $Version, $commit, $buildDate))
$parts.Add('# Source: NMMToolkit repo. Edit src\, then rebuild.')

# 1. Param block must be the first statement in the artifact
$parts.Add((Get-Content (Join-Path $root 'src\entry\00-param.ps1') -Raw -Encoding UTF8))

# 1b. Provenance as real variables, readable at runtime by -Version. Must come
# after the param block, which has to remain the first statement in the file.
#
# Escape single quotes by doubling them before interpolating into the
# single-quoted literals below - an operator-supplied -Version containing a
# quote (e.g. -Version "9.1.0'") would otherwise break out of the literal and
# fail the parse gate. Applied to $commit too, since it lands in the same kind
# of literal even though git output doesn't normally contain a quote.
$versionEscaped = $Version -replace "'", "''"
$commitEscaped  = $commit  -replace "'", "''"
$parts.Add('#region provenance')
$parts.Add(("`$script:ToolkitVersion   = '{0}'" -f $versionEscaped))
$parts.Add(("`$script:ToolkitCommit    = '{0}'" -f $commitEscaped))
$parts.Add(("`$script:ToolkitBuildDate = '{0:yyyy-MM-dd HH:mm}'" -f $buildDate))
$parts.Add('#endregion')

# 2. Core, in numeric-prefix order
foreach ($f in (Get-ChildItem (Join-Path $root 'src\core') -Filter *.ps1 | Sort-Object Name)) {
    $parts.Add(('#region core\{0}' -f $f.Name))
    $parts.Add((Get-Content $f.FullName -Raw -Encoding UTF8))
    $parts.Add('#endregion')
}

# 3. Registry: psd1 content is a valid hashtable literal, assigned directly
$parts.Add('#region registry')
$parts.Add('$script:RegistryData =')
$parts.Add((Get-Content (Join-Path $root 'src\registry\tools.psd1') -Raw -Encoding UTF8))
$parts.Add('#endregion')

# 4. Tools
$toolFiles = @(Get-ChildItem (Join-Path $root 'src\tools') -Recurse -Filter *.ps1 | Sort-Object FullName)
if ($toolFiles.Count -eq 0) { throw 'No .ps1 files found in src\tools - aborting build' }
# FullName groups tools by category dir then file; relative order is stable across machines
foreach ($f in $toolFiles) {
    $parts.Add(('#region tools\{0}\{1}' -f $f.Directory.Name, $f.Name))
    $parts.Add((Get-Content $f.FullName -Raw -Encoding UTF8))
    $parts.Add('#endregion')
}

# 5. Entry point last
$parts.Add((Get-Content (Join-Path $root 'src\entry\99-main.ps1') -Raw -Encoding UTF8))

Set-Content -Path $artifact -Value ($parts -join "`r`n") -Encoding UTF8

# Gate 1: parse
$tokens = $null; $parseErrors = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($artifact, [ref]$tokens, [ref]$parseErrors)
if ($parseErrors.Count -gt 0) {
    $parseErrors | ForEach-Object { Write-Host ('{0} (line {1})' -f $_.Message, $_.Extent.StartLineNumber) -ForegroundColor Red }
    throw ('Artifact has {0} parse error(s) - build failed' -f $parseErrors.Count)
}

# Gate 2: analyzer (errors only; warnings like PSAvoidUsingWriteHost are accepted)
if (-not $SkipAnalyzer) {
    Import-Module PSScriptAnalyzer
    $findings = Invoke-ScriptAnalyzer -Path $artifact -Severity Error
    if ($findings) {
        $findings | Format-Table RuleName, Line, Message -AutoSize | Out-String | Write-Host
        throw ('PSScriptAnalyzer found {0} error(s) - build failed' -f @($findings).Count)
    }
}

$sizeKB = [math]::Round((Get-Item $artifact).Length / 1KB)
Write-Host ('Built {0} ({1} KB, v{2} {3})' -f $artifact, $sizeKB, $Version, $commit) -ForegroundColor Green
