# Guards tools\Get-NmmGuiDiagnostic.ps1 against reporting the wrong verdict.
#
# Diagnostics age against the code they inspect, and a stale detector is worse
# than none because its output still looks authoritative. Two real failures on
# MATTHEWGR_L3, 2026-08-25:
#   1. It greps for the OLD by-name handler calls, so a CORRECTLY FIXED 9.3.3
#      artifact reported "NOT FOUND" - success in the vocabulary of failure.
#   2. Run twice in one PowerShell session it threw a raw WPF exception
#      ("Cannot perform requested operation because the Dispatcher shut down"),
#      because its own first run calls InvokeShutdown on that thread.
#
# Every case runs the real script in a SEPARATE process - it shuts down the
# Dispatcher of whatever thread it runs on, which would poison the suite.

BeforeAll {
    $script:RepoRoot = Split-Path $PSScriptRoot -Parent
    $script:Diag     = Join-Path $script:RepoRoot 'tools\Get-NmmGuiDiagnostic.ps1'
    $script:PsExe    = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'

    function New-FakeArtifact {
        # Minimal file with the shape Get-NmmGuiDiagnostic inspects: a version
        # banner it can parse, the six functions it looks for, and handler calls
        # in either the old (by-name) or new (captured reference) form.
        param(
            [Parameter(Mandatory)][ValidateSet('Old','Fixed')][string]$Shape,
            [Parameter(Mandatory)][string]$Version
        )
        $path = Join-Path ([System.IO.Path]::GetTempPath()) ('nmm-fake-{0}.ps1' -f [guid]::NewGuid().ToString('N'))
        $calls = if ($Shape -eq 'Old') {
@'
            Add-GuiOutputRecord -Sync $s -Record $rec
            Show-GuiPrompt -Sync $s -Request $req
            Show-GuiTextPrompt -Sync $s -Request $req
'@
        } else {
@'
            & $fnAddGuiOutputRecord -Sync $s -Record $rec
            & $fnShowGuiPrompt -Sync $s -Request $req
            & $fnShowGuiTextPrompt -Sync $s -Request $req
'@
        }
        $body = @"
#Requires -Version 5.1
# NMM System Toolkit v$Version (abc1234) | built 2026-08-25 00:00 | GENERATED by build.ps1 - DO NOT EDIT
# Source: fake, for tests only.
function Add-GuiOutputRecord { param(`$Sync, `$Record) }
function Show-GuiPrompt { param(`$Sync, `$Request) }
function Show-GuiTextPrompt { param(`$Sync, `$Request) }
function Start-GuiMenuSTA { }
function Start-GuiMenu { }
function New-NmmToolRunspace { }
function Invoke-FakeDrain {
    if (`$true) {
$calls
    }
}
"@
        [System.IO.File]::WriteAllText($path, $body, (New-Object System.Text.UTF8Encoding($false)))
        return $path
    }

    function Invoke-Diag {
        # Runs the diagnostic once in a fresh process and returns its report text.
        param([Parameter(Mandatory)][string]$ArtifactPath, [switch]$Twice)
        $outDir = Join-Path ([System.IO.Path]::GetTempPath()) ('nmm-diagout-' + [guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Force -Path $outDir | Out-Null
        $runs = if ($Twice) { 2 } else { 1 }
        $args = @('-NoProfile','-ExecutionPolicy','Bypass','-Command',
                  ("1..$runs | ForEach-Object {{ & '{0}' -Artifact '{1}' -OutDir '{2}' }}" -f $script:Diag, $ArtifactPath, $outDir))
        $out = (& $script:PsExe @args 2>&1 | Out-String)
        Remove-Item -LiteralPath $outDir -Recurse -Force -ErrorAction SilentlyContinue
        return $out
    }
}

Describe 'Get-NmmGuiDiagnostic reports the handler-call shape honestly' {

    It 'reports a fixed artifact as FIXED, never as NOT FOUND' {
        $fake = New-FakeArtifact -Shape Fixed -Version '9.3.3'
        try {
            $out = Invoke-Diag -ArtifactPath $fake
            $out | Should -Match 'FIXED'
            $out | Should -Not -Match 'NOT FOUND'
        } finally { Remove-Item -LiteralPath $fake -Force -ErrorAction SilentlyContinue }
    }

    It 'flags an artifact that still uses the by-name handler calls' {
        $fake = New-FakeArtifact -Shape Old -Version '9.3.1'
        try {
            $out = Invoke-Diag -ArtifactPath $fake
            $out | Should -Match 'BY-NAME'
            $out | Should -Match '9\.3\.3'
        } finally { Remove-Item -LiteralPath $fake -Force -ErrorAction SilentlyContinue }
    }
}

Describe 'Get-NmmGuiDiagnostic survives being run twice in one session' {

    It 'explains the shut-down Dispatcher instead of leaking a raw WPF exception' {
        $fake = New-FakeArtifact -Shape Fixed -Version '9.3.3'
        try {
            $out = Invoke-Diag -ArtifactPath $fake -Twice
            $out | Should -Match 'fresh PowerShell window'
            $out | Should -Not -Match 'Cannot perform requested operation because the Dispatcher shut down'
        } finally { Remove-Item -LiteralPath $fake -Force -ErrorAction SilentlyContinue }
    }
}
